// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc0cioNBzUlBHXYTce4CuiTtMbrPv44Fs',
    appId: '1:431017052825:web:15351121cee5457c7b0608',
    messagingSenderId: '431017052825',
    projectId: 'appaaja-bd44e',
    authDomain: 'appaaja-bd44e.firebaseapp.com',
    storageBucket: 'appaaja-bd44e.appspot.com',
    measurementId: 'G-H287JPDJQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtS0g_F5jQ9U9kiRgej2O0N9NIvAVRuTA',
    appId: '1:431017052825:android:724f895631edf5557b0608',
    messagingSenderId: '431017052825',
    projectId: 'appaaja-bd44e',
    storageBucket: 'appaaja-bd44e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIx-zs0pnu2AIU1a-yin3gcXyJHHzvjYI',
    appId: '1:431017052825:ios:a0b4ff48c1c4a9cd7b0608',
    messagingSenderId: '431017052825',
    projectId: 'appaaja-bd44e',
    storageBucket: 'appaaja-bd44e.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIx-zs0pnu2AIU1a-yin3gcXyJHHzvjYI',
    appId: '1:431017052825:ios:a0b4ff48c1c4a9cd7b0608',
    messagingSenderId: '431017052825',
    projectId: 'appaaja-bd44e',
    storageBucket: 'appaaja-bd44e.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc0cioNBzUlBHXYTce4CuiTtMbrPv44Fs',
    appId: '1:431017052825:web:33b8a050f258b4c47b0608',
    messagingSenderId: '431017052825',
    projectId: 'appaaja-bd44e',
    authDomain: 'appaaja-bd44e.firebaseapp.com',
    storageBucket: 'appaaja-bd44e.appspot.com',
    measurementId: 'G-WNBKSZF86E',
  );

}