// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5cIk-e2XKskcry2-qlNr28LElZYJnk_Q',
    appId: '1:568661363919:web:5d7f2ed660ab8c9b50fbba',
    messagingSenderId: '568661363919',
    projectId: 'kalkulator-8931a',
    authDomain: 'kalkulator-8931a.firebaseapp.com',
    storageBucket: 'kalkulator-8931a.appspot.com',
    measurementId: 'G-L2F8PSR2MT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzYhSsEoop1P5r6Z4DgDpUccpxDUeUTXE',
    appId: '1:568661363919:android:3cab5b114ca0df1f50fbba',
    messagingSenderId: '568661363919',
    projectId: 'kalkulator-8931a',
    storageBucket: 'kalkulator-8931a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsAnNULA9YBgZ2iLbixGNkOVawqEjH1Z4',
    appId: '1:568661363919:ios:186c2e03335924c450fbba',
    messagingSenderId: '568661363919',
    projectId: 'kalkulator-8931a',
    storageBucket: 'kalkulator-8931a.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsAnNULA9YBgZ2iLbixGNkOVawqEjH1Z4',
    appId: '1:568661363919:ios:186c2e03335924c450fbba',
    messagingSenderId: '568661363919',
    projectId: 'kalkulator-8931a',
    storageBucket: 'kalkulator-8931a.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5cIk-e2XKskcry2-qlNr28LElZYJnk_Q',
    appId: '1:568661363919:web:dbcd3160c468df4550fbba',
    messagingSenderId: '568661363919',
    projectId: 'kalkulator-8931a',
    authDomain: 'kalkulator-8931a.firebaseapp.com',
    storageBucket: 'kalkulator-8931a.appspot.com',
    measurementId: 'G-LDNT5B81EP',
  );
}
